name: PHPUnit Tests

on:
  push:
    branches:
      - dev**

jobs:
  test-php:
    name: ${{ matrix.php_versions }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php_versions: [8.2, 8.1, 8.0, 7.4, 7.3]
        os: [ubuntu-latest]

    # Include MySQL as a service
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install svn
        run: sudo apt-get install -y subversion

      - name: Verify DB exists
        run: mysql --ssl-mode=disabled --host 127.0.0.1 --port 33306 -uroot -proot -e "SHOW DATABASES LIKE 'wordpress_test'"

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}
          extension: mbstring, intl #optional, setup extensions
          ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
          coverage: xdebug #optional, setup coverage driver

      - name: Check PHP Version
        run: php -v

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php_versions }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php_versions }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Install WP Tests
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:33306 latest true

      - name: PHPUnit
        run: vendor/bin/phpunit --verbose -c phpunit.xml.dist
